In [6]:
#import bibliotek:
import pandas as pd

data = pd.read_html(
    'https://www.officialcharts.com/chart-news/the-best-selling-albums-of-all-time-on-the-official-uk-chart__15551/',
    header=0,
    flavor='html5lib'
)
data

[    POS                                   TITLE                    ARTIST  \
 0     1                           GREATEST HITS                     QUEEN
 1     2                    GOLD - GREATEST HITS                      ABBA
 2     3    SGT PEPPER'S LONELY HEARTS CLUB BAND                   BEATLES
 3     4                                      21                     ADELE
 4     5          WHAT'S THE STORY MORNING GLORY                     OASIS
 5     6                                THRILLER           MICHAEL JACKSON
 6     7               THE DARK SIDE OF THE MOON                PINK FLOYD
 7     8                        BROTHERS IN ARMS              DIRE STRAITS
 8     9                                     BAD           MICHAEL JACKSON
 9    10                        GREATEST HITS II                     QUEEN
 10   11                                 RUMOURS             FLEETWOOD MAC
 11   12               THE IMMACULATE COLLECTION                   MADONNA
 12   13                           BACK TO BLACK             AMY WINEHOUSE
 13   14                                   STARS                SIMPLY RED
 14   15                            COME ON OVER              SHANIA TWAIN
 15   16                                  LEGEND  BOB MARLEY & THE WAILERS
 16   17                          BACK TO BEDLAM               JAMES BLUNT
 17   18                             URBAN HYMNS                     VERVE
 18   19                         BAT OUT OF HELL                 MEAT LOAF
 19   20                                       1                   BEATLES
 20   21              BRIDGE OVER TROUBLED WATER         SIMON & GARFUNKEL
 21   22                           DIRTY DANCING       ORIGINAL SOUNDTRACK
 22   23                                  SPIRIT               LEONA LEWIS
 23   24                              CRAZY LOVE             MICHAEL BUBLE
 24   25                                NO ANGEL                      DIDO
 25   26                            WHITE LADDER                DAVID GRAY
 26   27                                      25                     ADELE
 27   28                         TALK ON CORNERS                     CORRS
 28   29                                   SPICE               SPICE GIRLS
 29   30                                THE FAME                 LADY GAGA
 30   31             A RUSH OF BLOOD TO THE HEAD                  COLDPLAY
 31   32                           LIFE FOR RENT                      DIDO
 32   33                       ONLY BY THE NIGHT             KINGS OF LEON
 33   34                         BEAUTIFUL WORLD                 TAKE THAT
 34   35                         HOPES AND FEARS                     KEANE
 35   36                         THE JOSHUA TREE                        U2
 36   37                   THE WAR OF THE WORLDS                JEFF WAYNE
 37   38                         SCISSOR SISTERS           SCISSOR SISTERS
 38   39                           BUT SERIOUSLY              PHIL COLLINS
 39   40                                     X&Y                  COLDPLAY
 40   41                      JAGGED LITTLE PILL         ALANIS MORISSETTE
 41   42                           TUBULAR BELLS             MIKE OLDFIELD
 42   43                             THE MAN WHO                    TRAVIS
 43   44                           TRACY CHAPMAN             TRACY CHAPMAN
 44   45                              PARACHUTES                  COLDPLAY
 45   46                           GREATEST HITS                      ABBA
 46   47                                  GREASE       ORIGINAL SOUNDTRACK
 47   48                 I'VE BEEN EXPECTING YOU           ROBBIE WILLIAMS
 48   49                                       X                ED SHEERAN
 49   50                       COME AWAY WITH ME               NORAH JONES
 50   51                               GRACELAND                PAUL SIMON
 51   52                      THE SOUND OF MUSIC   ORIGINAL CAST RECORDING
 52   53        LADIES & GENTLEMEN - THE BEST OF            GEORGE MICHAEL
 53   54                      TANGO IN THE NIGHT             FLEETWOOD MAC
 54   55                 THE MARSHALL MATHERS LP                    EMINEM
 55   56               SWING WHEN YOU'RE WINNING           ROBBIE WILLIAMS
 56   57                                PROGRESS                 TAKE THAT
 57   58                               EYES OPEN               SNOW PATROL
 58   59  NEVER FORGET - THE ULTIMATE COLLECTION                 TAKE THAT
 59   60                AUTOMATIC FOR THE PEOPLE                       REM

     YEAR  HIGH POSN
 0   1981          1
 1   1992          1
 2   1967          1
 3   2011          1
 4   1995          1
 5   1982          1
 6   1973          2
 7   1985          1
 8   1987          1
 9   1991          1
 10  1977          1
 11  1990          1
 12  2006          1
 13  1991          1
 14  1997          1
 15  1984          1
 16  2004          1
 17  1997          1
 18  1977          9
 19  2000          1
 20  1970          1
 21  1987          4
 22  2007          1
 23  2009          1
 24  2000          1
 25  1998          1
 26  2015          1
 27  1997          1
 28  1996          1
 29  2008          1
 30  2002          1
 31  2003          1
 32  2008          1
 33  2006          1
 34  2004          1
 35  1987          1
 36  1978          5
 37  2004          1
 38  1989          1
 39  2005          1
 40  1995          1
 41  1973          1
 42  1999          1
 43  1988          1
 44  2000          1
 45  1975          1
 46  1977          1
 47  1998          1
 48  2014          1
 49  2002          1
 50  1986          1
 51  1965          1
 52  1998          1
 53  1987          1
 54  2000          1
 55  2001          1
 56  2010          1
 57  2006          1
 58  2005          2
 59  1992          1  ]

In [7]:
# Wybieram pierwszą tabelę ze strony (read_html zwraca listę tabel)
df = data[0]

In [12]:
#Zamień nagłówki kolumn na polskie odpowiedniki:
df.rename(columns={
    'TITLE': 'TYTUL',
    'ARTIST': 'ARTYSTA',
    'YEAR': 'ROK',
    'HIGH POSN': 'MAX POZ'
}, inplace=True)

In [14]:
#Ilu pojedynczych artystów znajduje się na liście?
df['ARTYSTA'].nunique()

47

In [13]:
#Które zespoły pojawiają się najczęściej na liście?
df['ARTYSTA'].value_counts()

ARTYSTA
COLDPLAY                    3
TAKE THAT                   3
QUEEN                       2
ABBA                        2
BEATLES                     2
ADELE                       2
MICHAEL JACKSON             2
FLEETWOOD MAC               2
ORIGINAL SOUNDTRACK         2
DIDO                        2
ROBBIE WILLIAMS             2
OASIS                       1
PINK FLOYD                  1
DIRE STRAITS                1
MADONNA                     1
AMY WINEHOUSE               1
SIMPLY RED                  1
SHANIA TWAIN                1
BOB MARLEY & THE WAILERS    1
JAMES BLUNT                 1
VERVE                       1
MEAT LOAF                   1
SIMON & GARFUNKEL           1
LEONA LEWIS                 1
MICHAEL BUBLE               1
DAVID GRAY                  1
CORRS                       1
SPICE GIRLS                 1
LADY GAGA                   1
KINGS OF LEON               1
KEANE                       1
U2                          1
JEFF WAYNE                  1
SCISSOR SISTERS             1
PHIL COLLINS                1
ALANIS MORISSETTE           1
MIKE OLDFIELD               1
TRAVIS                      1
TRACY CHAPMAN               1
ED SHEERAN                  1
NORAH JONES                 1
PAUL SIMON                  1
ORIGINAL CAST RECORDING     1
GEORGE MICHAEL              1
EMINEM                      1
SNOW PATROL                 1
REM                         1
Name: count, dtype: int64

In [15]:
#Zmień nagłówki kolumn, tak aby każdy z nich rozpoczynał się od wielkiej litery, a pozostałe były wprowadzone małymi literami:
df.columns = df.columns.str.title()

In [20]:
#Wyrzuć z tabeli kolumnę ‘Max Poz’:
df.drop('Max Poz', axis=1, inplace=True)

In [21]:
#W którym roku wyszło najwięcej albumów znajdujących się na liście?:
df['Rok'].value_counts()

Rok
1987    4
2000    4
1977    3
2006    3
1997    3
2004    3
1998    3
1992    2
1995    2
1973    2
1991    2
2008    2
2002    2
2005    2
1981    1
1967    1
2011    1
1982    1
1985    1
1990    1
1984    1
1970    1
2007    1
2009    1
2015    1
1996    1
2003    1
1978    1
1989    1
1999    1
1988    1
1975    1
2014    1
1986    1
1965    1
2001    1
2010    1
Name: count, dtype: int64

In [22]:
#Ile albumów wydanych między 1960 a 1990 rokiem włącznie znajduje się na liście?
((df['Rok'] >= 1960) & (df['Rok'] <= 1990)).sum()

np.int64(22)

In [23]:
#W którym roku wydany został najmłodszy album na liście?:
df.sort_values('Rok', ascending=False).head(1)

    Pos Tytul Artysta   Rok
26   27    25   ADELE  2015

In [24]:
#Przygotuj listę najwcześniej wydanych albumów każdego artysty, który znalazł się na liście:
df.sort_values('Rok').groupby('Artysta').head(1)

,Pos,Tytul,Artysta,Rok
51,52,THE SOUND OF MUSIC,ORIGINAL CAST RECORDING,1965
2,3,SGT PEPPER'S LONELY HEARTS CLUB BAND,BEATLES,1967
20,21,BRIDGE OVER TROUBLED WATER,SIMON & GARFUNKEL,1970
6,7,THE DARK SIDE OF THE MOON,PINK FLOYD,1973
41,42,TUBULAR BELLS,MIKE OLDFIELD,1973
45,46,GREATEST HITS,ABBA,1975
18,19,BAT OUT OF HELL,MEAT LOAF,1977
10,11,RUMOURS,FLEETWOOD MAC,1977
46,47,GREASE,ORIGINAL SOUNDTRACK,1977
36,37,THE WAR OF THE WORLDS,JEFF WAYNE,1978
0,1,GREATEST HITS,QUEEN,1981
5,6,THRILLER,MICHAEL JACKSON,1982
15,16,LEGEND,BOB MARLEY & THE WAILERS,1984
7,8,BROTHERS IN ARMS,DIRE STRAITS,1985
50,51,GRACELAND,PAUL SIMON,1986
35,36,THE JOSHUA TREE,U2,1987
43,44,TRACY CHAPMAN,TRACY CHAPMAN,1988
38,39,BUT SERIOUSLY,PHIL COLLINS,1989
11,12,THE IMMACULATE COLLECTION,MADONNA,1990
13,14,STARS,SIMPLY RED,1991
59,60,AUTOMATIC FOR THE PEOPLE,REM,1992
40,41,JAGGED LITTLE PILL,ALANIS MORISSETTE,1995
4,5,WHAT'S THE STORY MORNING GLORY,OASIS,1995
28,29,SPICE,SPICE GIRLS,1996
27,28,TALK ON CORNERS,CORRS,1997
14,15,COME ON OVER,SHANIA TWAIN,1997
17,18,URBAN HYMNS,VERVE,1997
47,48,I'VE BEEN EXPECTING YOU,ROBBIE WILLIAMS,1998
52,53,LADIES & GENTLEMEN - THE BEST OF,GEORGE MICHAEL,1998
25,26,WHITE LADDER,DAVID GRAY,1998
42,43,THE MAN WHO,TRAVIS,1999
54,55,THE MARSHALL MATHERS LP,EMINEM,2000
24,25,NO ANGEL,DIDO,2000
44,45,PARACHUTES,COLDPLAY,2000
49,50,COME AWAY WITH ME,NORAH JONES,2002
37,38,SCISSOR SISTERS,SCISSOR SISTERS,2004
34,35,HOPES AND FEARS,KEANE,2004
16,17,BACK TO BEDLAM,JAMES BLUNT,2004
58,59,NEVER FORGET - THE ULTIMATE COLLECTION,TAKE THAT,2005
12,13,BACK TO BLACK,AMY WINEHOUSE,2006
57,58,EYES OPEN,SNOW PATROL,2006
22,23,SPIRIT,LEONA LEWIS,2007
32,33,ONLY BY THE NIGHT,KINGS OF LEON,2008
29,30,THE FAME,LADY GAGA,2008
23,24,CRAZY LOVE,MICHAEL BUBLE,2009
3,4,21,ADELE,2011
48,49,X,ED SHEERAN,2014

In [25]:
# Zapisuję listę najwcześniej wydanych albumów każdego artysty do pliku CSV:
df.sort_values('Rok').groupby('Artysta').head(1).to_csv('najwczesniejsze_albumy.csv', index=False)